import { TherapyPlan } from '@/types/plans'
import { PlanCategory } from '@/types/categories'

// Mock categories
export const mockCategories: PlanCategory[] = [
  {
    id: '1',
    name_ar: 'علاج النطق واللغة',
    name_en: 'Speech & Language Therapy',
    description_ar: 'علاج اضطرابات النطق واللغة',
    description_en: 'Treatment of speech and language disorders',
    color_code: '#10B981',
    icon_name: 'mic',
    sort_order: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '2',
    name_ar: 'العلاج الوظيفي',
    name_en: 'Occupational Therapy',
    description_ar: 'تطوير المهارات الحركية',
    description_en: 'Development of motor skills',
    color_code: '#F59E0B',
    icon_name: 'hand',
    sort_order: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '3',
    name_ar: 'العلاج السلوكي',
    name_en: 'Behavioral Therapy',
    description_ar: 'تعديل السلوكيات',
    description_en: 'Behavior modification',
    color_code: '#8B5CF6',
    icon_name: 'brain',
    sort_order: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
]

// Mock therapy plans
export const mockPlans: TherapyPlan[] = [
  {
    id: '1',
    name_ar: 'برنامج علاج النطق المتقدم',
    name_en: 'Advanced Speech Therapy Program',
    description_ar: 'برنامج شامل لعلاج اضطرابات النطق واللغة للأطفال من عمر 3-8 سنوات مع تركيز خاص على تحسين الوضوح',
    description_en: 'Comprehensive program for treating speech and language disorders in children aged 3-8 years',
    category_id: '1',
    category: mockCategories[0],
    duration_weeks: 12,
    sessions_per_week: 2,
    total_sessions: 24,
    price_per_session: 150,
    total_price: 3600,
    discount_percentage: 10,
    final_price: 3240,
    is_active: true,
    is_featured: true,
    prerequisites: 'تقييم أولي لحالة الطفل',
    target_age_min: 3,
    target_age_max: 8,
    max_students_per_session: 1,
    materials_needed: ['بطاقات صور', 'مرآة', 'ألعاب تفاعلية', 'كتب قصص'],
    learning_objectives: ['تحسين نطق الأصوات', 'زيادة المفردات', 'تطوير مهارات التواصل'],
    allowed_freeze_days: 14,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '2',
    name_ar: 'برنامج العلاج الوظيفي للأطفال',
    name_en: 'Pediatric Occupational Therapy',
    description_ar: 'برنامج مخصص لتطوير المهارات الحركية الدقيقة والكبيرة وتحسين التوازن',
    description_en: 'Specialized program for developing fine and gross motor skills',
    category_id: '2',
    category: mockCategories[1],
    duration_weeks: 16,
    sessions_per_week: 3,
    total_sessions: 48,
    price_per_session: 120,
    total_price: 5760,
    discount_percentage: 15,
    final_price: 4896,
    is_active: true,
    is_featured: true,
    prerequisites: 'فحص طبي شامل',
    target_age_min: 2,
    target_age_max: 10,
    max_students_per_session: 1,
    materials_needed: ['كرات علاجية', 'أدوات حرفية', 'ألعاب توازن'],
    learning_objectives: ['تحسين التوازن', 'تطوير المهارات الحركية', 'زيادة التناسق'],
    allowed_freeze_days: 21,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '3',
    name_ar: 'برنامج تعديل السلوك',
    name_en: 'Behavior Modification Program',
    description_ar: 'برنامج لتعديل السلوكيات غير المرغوبة وتعزيز السلوكيات الإيجابية',
    description_en: 'Program for modifying unwanted behaviors and reinforcing positive behaviors',
    category_id: '3',
    category: mockCategories[2],
    duration_weeks: 20,
    sessions_per_week: 2,
    total_sessions: 40,
    price_per_session: 180,
    total_price: 7200,
    discount_percentage: 5,
    final_price: 6840,
    is_active: true,
    is_featured: false,
    prerequisites: 'تقييم سلوكي شامل',
    target_age_min: 4,
    target_age_max: 12,
    max_students_per_session: 1,
    materials_needed: ['جداول التعزيز', 'بطاقات المراقبة', 'ألعاب تحفيزية'],
    learning_objectives: ['تقليل السلوك المشكل', 'زيادة الانتباه', 'تحسين التفاعل الاجتماعي'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '4',
    name_ar: 'برنامج علاج النطق الأساسي',
    name_en: 'Basic Speech Therapy',
    description_ar: 'برنامج أساسي لتحسين النطق',
    description_en: 'Basic program for speech improvement',
    category_id: '1',
    category: mockCategories[0],
    duration_weeks: 8,
    sessions_per_week: 1,
    total_sessions: 8,
    price_per_session: 100,
    total_price: 800,
    discount_percentage: 0,
    final_price: 800,
    is_active: false,
    is_featured: false,
    target_age_min: 5,
    target_age_max: 10,
    max_students_per_session: 1,
    materials_needed: ['مرآة', 'بطاقات'],
    learning_objectives: ['تحسين النطق'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '5',
    name_ar: 'برنامج العلاج المكثف',
    name_en: 'Intensive Therapy Program',
    description_ar: 'برنامج مكثف لحالات خاصة',
    description_en: 'Intensive program for special cases',
    category_id: '2',
    category: mockCategories[1],
    duration_weeks: 6,
    sessions_per_week: 5,
    total_sessions: 30,
    price_per_session: 200,
    total_price: 6000,
    discount_percentage: 20,
    final_price: 4800,
    is_active: true,
    is_featured: true,
    target_age_min: 1,
    target_age_max: 15,
    max_students_per_session: 1,
    materials_needed: ['أدوات متخصصة', 'معدات علاجية'],
    learning_objectives: ['تطوير مكثف للمهارات'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
]