name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run type check
      run: npm run type-check
      
    - name: Run tests with coverage
      run: npm run test:coverage
      env:
        # Mock environment variables for tests
        VITE_SUPABASE_URL: "https://mock.supabase.co"
        VITE_SUPABASE_ANON_KEY: "mock-key"
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Coverage Summary
      run: |
        echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "Coverage report has been generated and uploaded." >> $GITHUB_STEP_SUMMARY
        if [ -f coverage/coverage-summary.json ]; then
          echo "### Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat coverage/coverage-summary.json | jq -r '.total | "- **Lines:** \(.lines.pct)%\n- **Functions:** \(.functions.pct)%\n- **Branches:** \(.branches.pct)%\n- **Statements:** \(.statements.pct)%"' >> $GITHUB_STEP_SUMMARY
        fi